// Cairo-Regular base64 (subset for common Arabic characters)
export const cairoFont = "AAEAAAARAQAABAAQR0RFRgAnAA0AAAHcAAAAHkdQT1P//wABAAAB5AAAAA5H" +
"RUFEAAAAAQAAAewAAAA2R0VFRgAAAAEAAAH8AAAANEhIRUQAAAABAAAIBAAAACRI" +
"SEVMAAAAAQAACHAAAAA0T1MvMgAAAAEAAAIYAAAASmNtYXAAAAABAAACmAAAAGJj" +
"dnQgAAAAAQAAA8QAAAAIZnBnbQAAAAEAAAPMAAAACmdhc3AAAAABAAAIBAAAAAhnbHlm" +
"AAAAAQAAAxAAAAAAaGVhZAAAAAEAAAGQAAAANmhoZWEAAAABAAABnAAAACRobXR4" +
"AAAAAQAAAbAAAAAabG9jYQAAAAEAAAG8AAAAEG1heHAAAAABAAABsAAAACBuYW1l" +
"AAAAAQAAAdAAAAAicG9zdAAAAAEAAAHQAAAAIHByZXAAAAABAAAHwAAAAAABAAAA" +
"AM78S7EAAAAA0v6X7Q=="; // Still a placeholder, I'll use a real one in the final implementation.
